server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://outstagram-database.cljtipexbbfo.ap-northeast-2.rds.amazonaws.com:3306/downbit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: maewakka
    password: qhdks123!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: info

kakao:
  client-id: adbdc7ecd64cca6287cda818755e3bba
  redirect-uri: http://localhost:3000/user/kakao/callback

jwt:
  secret: dGhpcy1zZWNyZXQta2V5LWlzLXZlcnktaW1wb3J0YW50LWFuZC1hbnlvbmUtZG9uJ3Qta29udy10aGlzLXNlY3JldC1rZXk=
  access-token-expire-time: 18000000000
  refresh-token-expire-time: 604800000

